create table "public"."event_participants" (
    "id" bigint generated by default as identity not null,
    "event_id" uuid,
    "participant_id" uuid,
    "created_at" timestamp with time zone default now()
);


create table "public"."event_type" (
    "name" text not null,
    "description" text,
    "reference" text
);


create table "public"."events" (
    "id" uuid not null default gen_random_uuid(),
    "name" text,
    "event_type" text,
    "date_time" timestamp with time zone,
    "network_id" uuid,
    "consolidation_id" uuid,
    "participants_id" uuid,
    "attachments_id" uuid,
    "locations_id" uuid
);


create table "public"."files" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone default now(),
    "name" text,
    "mime_type" text,
    "size" double precision
);


create table "public"."locations" (
    "id" uuid not null default gen_random_uuid(),
    "coordinates" text,
    "address" text,
    "created_at" timestamp with time zone default now()
);


alter table "public"."logs" enable row level security;

CREATE UNIQUE INDEX event_participants_pkey ON public.event_participants USING btree (id);

CREATE UNIQUE INDEX event_type_pkey ON public.event_type USING btree (name);

CREATE UNIQUE INDEX events_pkey ON public.events USING btree (id);

CREATE UNIQUE INDEX files_pkey ON public.files USING btree (id);

CREATE UNIQUE INDEX locations_pkey ON public.locations USING btree (id);

alter table "public"."event_participants" add constraint "event_participants_pkey" PRIMARY KEY using index "event_participants_pkey";

alter table "public"."event_type" add constraint "event_type_pkey" PRIMARY KEY using index "event_type_pkey";

alter table "public"."events" add constraint "events_pkey" PRIMARY KEY using index "events_pkey";

alter table "public"."files" add constraint "files_pkey" PRIMARY KEY using index "files_pkey";

alter table "public"."locations" add constraint "locations_pkey" PRIMARY KEY using index "locations_pkey";

alter table "public"."event_participants" add constraint "event_participants_event_id_fkey" FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE CASCADE not valid;

alter table "public"."event_participants" validate constraint "event_participants_event_id_fkey";

alter table "public"."event_participants" add constraint "event_participants_participant_id_fkey" FOREIGN KEY (participant_id) REFERENCES disciples(id) ON DELETE CASCADE not valid;

alter table "public"."event_participants" validate constraint "event_participants_participant_id_fkey";

alter table "public"."events" add constraint "events_attachments_id_fkey" FOREIGN KEY (attachments_id) REFERENCES files(id) ON DELETE CASCADE not valid;

alter table "public"."events" validate constraint "events_attachments_id_fkey";

alter table "public"."events" add constraint "events_consolidation_id_fkey" FOREIGN KEY (consolidation_id) REFERENCES consolidators(id) ON DELETE CASCADE not valid;

alter table "public"."events" validate constraint "events_consolidation_id_fkey";

alter table "public"."events" add constraint "events_event_type_fkey" FOREIGN KEY (event_type) REFERENCES event_type(name) ON DELETE CASCADE not valid;

alter table "public"."events" validate constraint "events_event_type_fkey";

alter table "public"."events" add constraint "events_locations_id_fkey" FOREIGN KEY (locations_id) REFERENCES locations(id) ON DELETE CASCADE not valid;

alter table "public"."events" validate constraint "events_locations_id_fkey";

alter table "public"."events" add constraint "events_network_id_fkey" FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE not valid;

alter table "public"."events" validate constraint "events_network_id_fkey";

alter table "public"."events" add constraint "events_participants_id_fkey" FOREIGN KEY (participants_id) REFERENCES disciples(id) ON DELETE CASCADE not valid;

alter table "public"."events" validate constraint "events_participants_id_fkey";


alter table "storage"."objects" add constraint "objects_bucket_id_fkey" FOREIGN KEY (bucket_id) REFERENCES storage.buckets(id) not valid;

alter table "storage"."objects" validate constraint "objects_bucket_id_fkey";


