alter table "auth"."refresh_tokens" drop constraint "refresh_tokens_session_id_fkey";


create table "public"."consolidation_lessons" (
    "name" text,
    "code" text not null,
    "title" text
);


create table "public"."consolidations" (
    "id" uuid not null default uuid_generate_v4(),
    "consolidator_id" uuid,
    "disciple_id" uuid,
    "is_deleted" boolean default false,
    "created_at" timestamp with time zone default now(),
    "lesson_code" text,
    "status" text default 'DRAFT'::text
);


create table "public"."consolidators" (
    "id" uuid not null default uuid_generate_v4(),
    "created_at" timestamp with time zone default now(),
    "disciples_id" uuid,
    "is_deleted" boolean default false
);


create table "public"."consolidators_lesson" (
    "id" uuid not null default uuid_generate_v4(),
    "created_at" timestamp with time zone default now(),
    "code" text,
    "consolidators_id" uuid,
    "is_completed" boolean default false
);


create table "public"."disciples" (
    "id" uuid not null default uuid_generate_v4(),
    "created_at" timestamp with time zone default now(),
    "first_name" text,
    "middle_name" text,
    "last_name" text,
    "gender" text,
    "address" text,
    "contact_number" text,
    "birthday" date,
    "is_deleted" boolean,
    "email" text,
    "sex" text,
    "status" text default 'Active'::text,
    "img_url" text
);


create table "public"."logs" (
    "id" bigint generated by default as identity not null,
    "message" text,
    "attributes" json,
    "pathname" text,
    "created_at" timestamp with time zone default now()
);


create table "public"."network_disciples" (
    "id" uuid not null default uuid_generate_v4(),
    "network_id" uuid,
    "disciple_id" uuid,
    "created_at" timestamp with time zone default now(),
    "is_deleted" boolean default false,
    "status" text default 'Active'::text
);


create table "public"."network_networks" (
    "id" uuid not null default uuid_generate_v4(),
    "created_at" timestamp with time zone default now(),
    "main_network_id" uuid,
    "networks_id" uuid,
    "status" text default 'Active'::text
);


create table "public"."networks" (
    "id" uuid not null default uuid_generate_v4(),
    "name" text,
    "created_at" timestamp with time zone default now(),
    "is_deleted" boolean default false,
    "discipler_id" uuid,
    "status" text default 'Active'::text
);


create table "public"."sessions" (
    "id" uuid not null default gen_random_uuid(),
    "client_id" text,
    "user_id" uuid,
    "valid_until" timestamp with time zone
);


create table "public"."vips" (
    "id" uuid not null default uuid_generate_v4(),
    "created_at" timestamp with time zone default now(),
    "disciple_id" uuid
);


CREATE UNIQUE INDEX consolidation_lessons_pkey ON public.consolidation_lessons USING btree (code);

CREATE UNIQUE INDEX consolidations_pkey ON public.consolidations USING btree (id);

CREATE UNIQUE INDEX consolidators_lesson_pkey ON public.consolidators_lesson USING btree (id);

CREATE UNIQUE INDEX consolidators_pkey ON public.consolidators USING btree (id);

CREATE UNIQUE INDEX disciples_email_key ON public.disciples USING btree (email);

CREATE UNIQUE INDEX disciples_pkey ON public.disciples USING btree (id);

CREATE UNIQUE INDEX logs_pkey ON public.logs USING btree (id);

CREATE UNIQUE INDEX network_disciples_pkey ON public.network_disciples USING btree (id);

CREATE UNIQUE INDEX network_networks_pkey ON public.network_networks USING btree (id);

CREATE UNIQUE INDEX networks_pkey ON public.networks USING btree (id);

CREATE UNIQUE INDEX sessions_pkey ON public.sessions USING btree (id);

CREATE UNIQUE INDEX vips_pkey ON public.vips USING btree (id);

alter table "public"."consolidation_lessons" add constraint "consolidation_lessons_pkey" PRIMARY KEY using index "consolidation_lessons_pkey";

alter table "public"."consolidations" add constraint "consolidations_pkey" PRIMARY KEY using index "consolidations_pkey";

alter table "public"."consolidators" add constraint "consolidators_pkey" PRIMARY KEY using index "consolidators_pkey";

alter table "public"."consolidators_lesson" add constraint "consolidators_lesson_pkey" PRIMARY KEY using index "consolidators_lesson_pkey";

alter table "public"."disciples" add constraint "disciples_pkey" PRIMARY KEY using index "disciples_pkey";

alter table "public"."logs" add constraint "logs_pkey" PRIMARY KEY using index "logs_pkey";

alter table "public"."network_disciples" add constraint "network_disciples_pkey" PRIMARY KEY using index "network_disciples_pkey";

alter table "public"."network_networks" add constraint "network_networks_pkey" PRIMARY KEY using index "network_networks_pkey";

alter table "public"."networks" add constraint "networks_pkey" PRIMARY KEY using index "networks_pkey";

alter table "public"."sessions" add constraint "sessions_pkey" PRIMARY KEY using index "sessions_pkey";

alter table "public"."vips" add constraint "vips_pkey" PRIMARY KEY using index "vips_pkey";

alter table "public"."consolidations" add constraint "consolidations_consolidator_id_fkey" FOREIGN KEY (consolidator_id) REFERENCES disciples(id) not valid;

alter table "public"."consolidations" validate constraint "consolidations_consolidator_id_fkey";

alter table "public"."consolidations" add constraint "consolidations_disciple_id_fkey" FOREIGN KEY (disciple_id) REFERENCES disciples(id) not valid;

alter table "public"."consolidations" validate constraint "consolidations_disciple_id_fkey";

alter table "public"."consolidations" add constraint "consolidations_lesson_code_fkey" FOREIGN KEY (lesson_code) REFERENCES consolidation_lessons(code) not valid;

alter table "public"."consolidations" validate constraint "consolidations_lesson_code_fkey";

alter table "public"."consolidators" add constraint "consolidators_disciples_id_fkey" FOREIGN KEY (disciples_id) REFERENCES disciples(id) not valid;

alter table "public"."consolidators" validate constraint "consolidators_disciples_id_fkey";

alter table "public"."consolidators_lesson" add constraint "consolidators_lesson_code_fkey" FOREIGN KEY (code) REFERENCES consolidation_lessons(code) not valid;

alter table "public"."consolidators_lesson" validate constraint "consolidators_lesson_code_fkey";

alter table "public"."consolidators_lesson" add constraint "consolidators_lesson_consolidators_id_fkey" FOREIGN KEY (consolidators_id) REFERENCES consolidators(id) not valid;

alter table "public"."consolidators_lesson" validate constraint "consolidators_lesson_consolidators_id_fkey";

alter table "public"."disciples" add constraint "disciples_email_key" UNIQUE using index "disciples_email_key";

alter table "public"."network_disciples" add constraint "network_disciples_disciple_id_fkey" FOREIGN KEY (disciple_id) REFERENCES disciples(id) not valid;

alter table "public"."network_disciples" validate constraint "network_disciples_disciple_id_fkey";

alter table "public"."network_disciples" add constraint "network_disciples_network_id_fkey" FOREIGN KEY (network_id) REFERENCES networks(id) not valid;

alter table "public"."network_disciples" validate constraint "network_disciples_network_id_fkey";

alter table "public"."network_networks" add constraint "network_networks_main_network_id_fkey" FOREIGN KEY (main_network_id) REFERENCES networks(id) not valid;

alter table "public"."network_networks" validate constraint "network_networks_main_network_id_fkey";

alter table "public"."network_networks" add constraint "network_networks_networks_id_fkey" FOREIGN KEY (networks_id) REFERENCES networks(id) not valid;

alter table "public"."network_networks" validate constraint "network_networks_networks_id_fkey";

alter table "public"."networks" add constraint "networks_discipler_id_fkey" FOREIGN KEY (discipler_id) REFERENCES disciples(id) not valid;

alter table "public"."networks" validate constraint "networks_discipler_id_fkey";

alter table "public"."sessions" add constraint "sessions_user_id_fkey" FOREIGN KEY (user_id) REFERENCES disciples(id) not valid;

alter table "public"."sessions" validate constraint "sessions_user_id_fkey";

alter table "public"."vips" add constraint "vips_disciple_id_fkey" FOREIGN KEY (disciple_id) REFERENCES disciples(id) not valid;

alter table "public"."vips" validate constraint "vips_disciple_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.get_auth_users()
 RETURNS SETOF auth.users
 LANGUAGE sql
AS $function$
select * from auth.users
$function$
;

CREATE OR REPLACE FUNCTION public.get_network_leaders()
 RETURNS SETOF disciples
 LANGUAGE sql
AS $function$
select distinct on (discipler_id) disciples.* from networks
inner join disciples on networks.discipler_id = disciples.id
$function$
;

create or replace view "public"."users" as  SELECT users.instance_id,
    users.id,
    users.aud,
    users.role,
    users.email,
    users.encrypted_password,
    users.email_confirmed_at,
    users.invited_at,
    users.confirmation_token,
    users.confirmation_sent_at,
    users.recovery_token,
    users.recovery_sent_at,
    users.email_change_token_new,
    users.email_change,
    users.email_change_sent_at,
    users.last_sign_in_at,
    users.raw_app_meta_data,
    users.raw_user_meta_data,
    users.is_super_admin,
    users.created_at,
    users.updated_at,
    users.phone,
    users.phone_confirmed_at,
    users.phone_change,
    users.phone_change_token,
    users.phone_change_sent_at,
    users.confirmed_at,
    users.email_change_token_current,
    users.email_change_confirm_status,
    users.banned_until,
    users.reauthentication_token,
    users.reauthentication_sent_at,
    users.is_sso_user,
    users.deleted_at
   FROM auth.users;



alter table "storage"."objects" drop constraint "objects_owner_fkey";

alter table "storage"."objects" alter column "id" drop default;

alter table "storage"."objects" add constraint "objects_bucket_id_fkey" FOREIGN KEY (bucket_id) REFERENCES storage.buckets(id) not valid;

alter table "storage"."objects" validate constraint "objects_bucket_id_fkey";


