
SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

CREATE EXTENSION IF NOT EXISTS "pgsodium" WITH SCHEMA "pgsodium";

ALTER SCHEMA "public" OWNER TO "postgres";

CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";

CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "pgjwt" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";

CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";

CREATE FUNCTION "public"."get_auth_users"() RETURNS SETOF "auth"."users"
    LANGUAGE "sql"
    AS $$
select * from auth.users
$$;

ALTER FUNCTION "public"."get_auth_users"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";

CREATE TABLE "public"."disciples" (
    "id" "uuid" DEFAULT "extensions"."uuid_generate_v4"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "first_name" "text",
    "middle_name" "text",
    "last_name" "text",
    "gender" "text",
    "address" "text",
    "contact_number" "text",
    "birthday" "date",
    "is_deleted" boolean,
    "email" "text",
    "sex" "text",
    "status" "text" DEFAULT 'Active'::"text",
    "img_url" "text"
);

ALTER TABLE "public"."disciples" OWNER TO "postgres";

CREATE FUNCTION "public"."get_network_leaders"() RETURNS SETOF "public"."disciples"
    LANGUAGE "sql"
    AS $$
select distinct on (discipler_id) disciples.* from networks
inner join disciples on networks.discipler_id = disciples.id
$$;

ALTER FUNCTION "public"."get_network_leaders"() OWNER TO "postgres";

CREATE TABLE "public"."consolidation_lessons" (
    "name" "text",
    "code" "text" NOT NULL,
    "title" "text"
);

ALTER TABLE "public"."consolidation_lessons" OWNER TO "postgres";

CREATE TABLE "public"."consolidations" (
    "id" "uuid" DEFAULT "extensions"."uuid_generate_v4"() NOT NULL,
    "consolidator_id" "uuid",
    "disciple_id" "uuid",
    "is_deleted" boolean DEFAULT false,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "lesson_code" "text",
    "status" "text" DEFAULT 'DRAFT'::"text"
);

ALTER TABLE "public"."consolidations" OWNER TO "postgres";

CREATE TABLE "public"."consolidators" (
    "id" "uuid" DEFAULT "extensions"."uuid_generate_v4"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "disciples_id" "uuid",
    "is_deleted" boolean DEFAULT false
);

ALTER TABLE "public"."consolidators" OWNER TO "postgres";

CREATE TABLE "public"."consolidators_lesson" (
    "id" "uuid" DEFAULT "extensions"."uuid_generate_v4"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "code" "text",
    "consolidators_id" "uuid",
    "is_completed" boolean DEFAULT false
);

ALTER TABLE "public"."consolidators_lesson" OWNER TO "postgres";

CREATE TABLE "public"."logs" (
    "id" bigint NOT NULL,
    "message" "text",
    "attributes" "json",
    "pathname" "text",
    "created_at" timestamp with time zone DEFAULT "now"()
);

ALTER TABLE "public"."logs" OWNER TO "postgres";

ALTER TABLE "public"."logs" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."logs_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE "public"."network_disciples" (
    "id" "uuid" DEFAULT "extensions"."uuid_generate_v4"() NOT NULL,
    "network_id" "uuid",
    "disciple_id" "uuid",
    "created_at" timestamp with time zone DEFAULT "now"(),
    "is_deleted" boolean DEFAULT false,
    "status" "text" DEFAULT 'Active'::"text"
);

ALTER TABLE "public"."network_disciples" OWNER TO "postgres";

CREATE TABLE "public"."network_networks" (
    "id" "uuid" DEFAULT "extensions"."uuid_generate_v4"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "main_network_id" "uuid",
    "networks_id" "uuid",
    "status" "text" DEFAULT 'Active'::"text"
);

ALTER TABLE "public"."network_networks" OWNER TO "postgres";

CREATE TABLE "public"."networks" (
    "id" "uuid" DEFAULT "extensions"."uuid_generate_v4"() NOT NULL,
    "name" "text",
    "created_at" timestamp with time zone DEFAULT "now"(),
    "is_deleted" boolean DEFAULT false,
    "discipler_id" "uuid",
    "status" "text" DEFAULT 'Active'::"text"
);

ALTER TABLE "public"."networks" OWNER TO "postgres";

CREATE TABLE "public"."sessions" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "client_id" "text",
    "user_id" "uuid",
    "valid_until" timestamp with time zone
);

ALTER TABLE "public"."sessions" OWNER TO "postgres";

CREATE VIEW "public"."users" AS
 SELECT "users"."instance_id",
    "users"."id",
    "users"."aud",
    "users"."role",
    "users"."email",
    "users"."encrypted_password",
    "users"."email_confirmed_at",
    "users"."invited_at",
    "users"."confirmation_token",
    "users"."confirmation_sent_at",
    "users"."recovery_token",
    "users"."recovery_sent_at",
    "users"."email_change_token_new",
    "users"."email_change",
    "users"."email_change_sent_at",
    "users"."last_sign_in_at",
    "users"."raw_app_meta_data",
    "users"."raw_user_meta_data",
    "users"."is_super_admin",
    "users"."created_at",
    "users"."updated_at",
    "users"."phone",
    "users"."phone_confirmed_at",
    "users"."phone_change",
    "users"."phone_change_token",
    "users"."phone_change_sent_at",
    "users"."confirmed_at",
    "users"."email_change_token_current",
    "users"."email_change_confirm_status",
    "users"."banned_until",
    "users"."reauthentication_token",
    "users"."reauthentication_sent_at",
    "users"."is_sso_user",
    "users"."deleted_at"
   FROM "auth"."users";

ALTER TABLE "public"."users" OWNER TO "postgres";

CREATE TABLE "public"."vips" (
    "id" "uuid" DEFAULT "extensions"."uuid_generate_v4"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "disciple_id" "uuid"
);

ALTER TABLE "public"."vips" OWNER TO "postgres";

ALTER TABLE ONLY "public"."consolidation_lessons"
    ADD CONSTRAINT "consolidation_lessons_pkey" PRIMARY KEY ("code");

ALTER TABLE ONLY "public"."consolidations"
    ADD CONSTRAINT "consolidations_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."consolidators_lesson"
    ADD CONSTRAINT "consolidators_lesson_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."consolidators"
    ADD CONSTRAINT "consolidators_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."disciples"
    ADD CONSTRAINT "disciples_email_key" UNIQUE ("email");

ALTER TABLE ONLY "public"."disciples"
    ADD CONSTRAINT "disciples_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."logs"
    ADD CONSTRAINT "logs_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."network_disciples"
    ADD CONSTRAINT "network_disciples_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."network_networks"
    ADD CONSTRAINT "network_networks_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."networks"
    ADD CONSTRAINT "networks_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."sessions"
    ADD CONSTRAINT "sessions_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."vips"
    ADD CONSTRAINT "vips_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."consolidations"
    ADD CONSTRAINT "consolidations_consolidator_id_fkey" FOREIGN KEY ("consolidator_id") REFERENCES "public"."disciples"("id");

ALTER TABLE ONLY "public"."consolidations"
    ADD CONSTRAINT "consolidations_disciple_id_fkey" FOREIGN KEY ("disciple_id") REFERENCES "public"."disciples"("id");

ALTER TABLE ONLY "public"."consolidations"
    ADD CONSTRAINT "consolidations_lesson_code_fkey" FOREIGN KEY ("lesson_code") REFERENCES "public"."consolidation_lessons"("code");

ALTER TABLE ONLY "public"."consolidators"
    ADD CONSTRAINT "consolidators_disciples_id_fkey" FOREIGN KEY ("disciples_id") REFERENCES "public"."disciples"("id");

ALTER TABLE ONLY "public"."consolidators_lesson"
    ADD CONSTRAINT "consolidators_lesson_code_fkey" FOREIGN KEY ("code") REFERENCES "public"."consolidation_lessons"("code");

ALTER TABLE ONLY "public"."consolidators_lesson"
    ADD CONSTRAINT "consolidators_lesson_consolidators_id_fkey" FOREIGN KEY ("consolidators_id") REFERENCES "public"."consolidators"("id");

ALTER TABLE ONLY "public"."network_disciples"
    ADD CONSTRAINT "network_disciples_disciple_id_fkey" FOREIGN KEY ("disciple_id") REFERENCES "public"."disciples"("id");

ALTER TABLE ONLY "public"."network_disciples"
    ADD CONSTRAINT "network_disciples_network_id_fkey" FOREIGN KEY ("network_id") REFERENCES "public"."networks"("id");

ALTER TABLE ONLY "public"."network_networks"
    ADD CONSTRAINT "network_networks_main_network_id_fkey" FOREIGN KEY ("main_network_id") REFERENCES "public"."networks"("id");

ALTER TABLE ONLY "public"."network_networks"
    ADD CONSTRAINT "network_networks_networks_id_fkey" FOREIGN KEY ("networks_id") REFERENCES "public"."networks"("id");

ALTER TABLE ONLY "public"."networks"
    ADD CONSTRAINT "networks_discipler_id_fkey" FOREIGN KEY ("discipler_id") REFERENCES "public"."disciples"("id");

ALTER TABLE ONLY "public"."sessions"
    ADD CONSTRAINT "sessions_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."disciples"("id");

ALTER TABLE ONLY "public"."vips"
    ADD CONSTRAINT "vips_disciple_id_fkey" FOREIGN KEY ("disciple_id") REFERENCES "public"."disciples"("id");

REVOKE USAGE ON SCHEMA "public" FROM PUBLIC;

RESET ALL;
